### ISSUE TITLE
geen update live versie

### ISSUE THREAD

**Issue by Theo-denBlanken** [Pepijn-de-koning/Fro-Bem#6]
Daar staat nog steeds  `<div class="container__geelvlak">` en met deze class heb ik de meeste problemen.
Er is geen block `container`.
Ook de 'verbeterde' `<div class="geelvlak__container">` verondersteld een block `geelvlak` welke niet is aangetroffen.....

**Comment by Pepijn-de-koning** [comment]
live versie was wel geupdate maar het is niet zo handig als u een half uur van te voren deze issue geeft en daarna een cijver
